### ISSUE TITLE
How to install dialects?

### ISSUE THREAD

**Issue by arne-cl** [amagidow/dialects#1]
Dear Alex,

I don't see a `setup.py` in your project. How is it supposed to be installed and run?

Best regards,
Arne

**Comment by amagidow** [comment]
Dear Arne,

I haven't included a setup.py because honestly I don't know how to write 
one (very sorry!), and because I'm not sure what value there would be in 
installing the dialects stuff as an app per se. I think I'd just 
download it via the source and run it from there.

What are you hoping to use the project for?

Also you're the first person to express interest in the project's source 
so far, so I'm happy to work with you to make it fit your needs better.

Alex

**Comment by arne-cl** [comment]
Hi Alex,

okay, so if I don't need to install it, how do I run it?

``` python
/tmp/dialects $ python manage.py 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/dialects/dialects/settings.py", line 14, in <module>
    from dialects.localsettings import *
ImportError: No module named localsettings
```

``` python
/tmp/dialects/dialects $ python wsgi.py
Traceback (most recent call last):
  File "wsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/arne/.virtualenvs/notebook/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named dialects.settings
```

Best,
Arne

**Comment by amagidow** [comment]
Ahh, ok. I see some of the problems here. I'm crazy busy today. I'll try 
to get to this tomorrow, is that ok?

Basically, there needs to be a localsettings file in order to load 
settings that have things like passwords, etc, that I don't want on 
GitHub, or which have a local configuration (i.e. debug mode on my local 
machine, but normal mode on the server). I'll put together a dummy 
version of the file and put it on GitHub.

Also, I used python 3 for the project, so I am not 100% sure if it will 
work with Python 2.

This is my first open source project, so please bear with me a bit. 
Sorry for any inconvenience.

Alex

**Comment by arne-cl** [comment]
Take your time. I'll see if I can get it running using Python 3.

**Comment by amagidow** [comment]
Yeah, just make sure you have a localsettings.py file to do things like 
build the database connection, and to hold the Django SECRET_KEY.

**Comment by arne-cl** [comment]
Could you provide me with an example `localsettings.py`? I have no experience with
(Django) web development at all.

**Comment by amagidow** [comment]
Yes, I've attached an example version. Note that you'll have to redefine 
the secret key, or add an environmental variable named DIALECTDBSK for 
Django to be satisfied, and update the database information as appropriate.

Let me know if that helps.
Alex

**Comment by arne-cl** [comment]
The attachment seems to be missing.

**Comment by amagidow** [comment]
I'm not sure if I forgot to attach it or if the system ate it. I'm 
pasting it in text below also in case of the latter.

## localsettings.py

# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/1.6/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

import os#Used to import secret key from environment variable

#####I use an environmental variable for the secret key, but you can use 
something else.###
SECRET_KEY = os.environ['DIALECTDBSK']

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

#There are some differences in Middleware between the debug and 
production versions
MIDDLEWARE_CLASSES = (
         'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
     'django.middleware.common.CommonMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
     'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

#Different local apps for debug and production versions

LOCAL_INSTALLED_APPS = ('django_extensions',
                         )

#Debug version settings
SESSION_COOKIE_SECURE=False
CSRF_COOKIE_SECURE=False

TEMPLATE_DEBUG = True

#Make sure you update the User and Password for the database as appropriate.
DATABASES = {
     'default': {
         'ENGINE': 'django.contrib.gis.db.backends.postgis',
         'NAME': 'arabicDialectProject',
         'USER': 'USERNAME GOES HERE',
         'PASSWORD': 'DATABASE USER PASSWORD GOES HERE',
         'HOST': '127.0.0.1',
         'PORT': '5432',

```
 }
```

}

ALLOWED_HOSTS = [
     "database-of-arabic-dialects.org"
]

**Comment by xrotwang** [comment]
@arne-cl Hi Arne, what exactly are you trying to accomplish? Are you interested in the arabic dialects or a database framework for linguistic data in general? If the latter, maybe https://github.com/clld/clld would fit your bill?

**Comment by arne-cl** [comment]
If you reply to Github issues via email, attachments will be ignored.

Could you please run `pip freeze > requirements.txt` and post the result?

``` python
$ DIALECTDBSK=foo python3 manage.py 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.4/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'leaflet'
```

I found a number of missing modules this way, but in the case of `leaflet`,
I couldn't install it via pip.

``` python
$ pip3 install --upgrade django-leaflet
Downloading/unpacking django-leaflet
  Downloading django-leaflet-0.16.0.zip (231kB): 231kB downloaded
  Running setup.py (path:/tmp/pip_build_root/django-leaflet/setup.py) egg_info for package django-leaflet
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/django-leaflet/setup.py", line 19, in <module>
        long_description=open(os.path.join(here, 'README.rst')).read() + '\n\n' +
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14276: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/django-leaflet/setup.py", line 19, in <module>

    long_description=open(os.path.join(here, 'README.rst')).read() + '\n\n' +

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14276: ordinal not in range(128)
```

**Comment by arne-cl** [comment]
@xrotwang Thanks for the tip, Robert. I am interested in _this_ particular database / framework for linguistic data, though.

**Comment by amagidow** [comment]
Below is the output of pip freeze. I do seem to recall that some 
packages were difficult to install, though I don't recall having 
difficulty with leaflet.  I'm sorry, but there are some packages there 
that are not relevant to the project - I am not sure how to find a list 
of required packages just for the Django project itself.

Also, I'm glad to hear you are particularly interested in this project. 
Please feel free to email me at the email address listed in the readme 
if you'd like to discuss the project further.

bibtexparser==0.6.0
colorama==0.3.3
colour==0.1.1
Django==1.8.2
django-appconf==0.6
django-autocomplete-light==2.0.9
django-classy-tags==0.6.1
django-extensions==1.5.5
django-geojson==2.6.0
django-geoposition==0.2.2
django-jinja==1.4.1
django-leaflet==0.15.2
django-polymorphic==0.6.1
django-stronghold==0.2.7
dot2tex==2.9.0
geojson==1.0.9
geopy==1.8.1
graphviz==0.4.4
htmlmin==0.1.6
Jinja2==2.7.3
lribeiro.django.primeui==0.1
MarkupSafe==0.23
modernize==0.4
ply==3.6
psycopg2==2.5.4
py==1.4.26
pydot==1.0.29
pyoo==1.0
pyparsing==2.0.3
pytest==2.6.4
six==1.9.0
slimit==0.8.1
South==1.0.2

**Comment by arne-cl** [comment]
Dear Alex,

using your `requirements.txt` seems to work, but I still don't know how to start and use
the web application.

``` python
$ /opt/dialects/dialects# python3 settings.py

Traceback (most recent call last):
  File "settings.py", line 14, in <module>
    from dialects.localsettings import *
ImportError: No module named 'dialects'

$ /opt/dialects/dialects# python3 urls.py

Traceback (most recent call last):
  File "urls.py", line 2, in <module>
    from dialectsDB.views import *
ImportError: No module named 'dialectsDB'


$ /opt/dialects/dialects# python3 wsgi.py 

Traceback (most recent call last):
  File "wsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.4/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python3.4/dist-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2189, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'dialects'
```

**Comment by amagidow** [comment]
Dear Arne,

I'm glad the `requirements.txt` worked for you! 

To run the project using Django, you need to run the manage.py script, not `settings.py/urls.pr/wsgi.py`. The documentation for `manage.py` can be found here:
https://docs.djangoproject.com/en/1.8/ref/django-admin/

If you would like to see the webpages, you would want to use the `runserver` command, but you may need to run `migrate` and similar commands to create the database first, though of course your local settings file will need to have appropriate login information for your local database server first. Django's documentation is generally some of the best I've seen, and there're lots of Q&As on StackExchange which are very helpful.

Again, I'm very sorry if I haven't been more helpful to date. I'm an assistant professor with a lot on my plate, and this is my first open source project. I don't recall having quite as much difficulty moving it to the server as you are having in installing it, but I should look into making it more portable come winter break.

**Comment by arne-cl** [comment]
Dear Alex,

thank you for your fast response. I don't really have time to dig into Django configurations
right now, but at least I made your code talk to my postgres server.
I put all the steps that I took into a Docker file, so you can easily reproduce them
when you have more time.

https://github.com/nlpdocker/dialects-docker

``` python
$ /opt/dialects# DIALECTDBSK=postgres python3 manage.py runserver

[...]

System check identified 2 issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fb75911f950>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.4/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.4/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  database "arabicDialectProject" does not exist
```
